# Generated by Django 6.0.6 on 2026-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0004_skillcategory_remove_skill_icon_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField()),
            ],
        ),
    ]
